version: '3.8'

services:
  carparts_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: "carparts_api:${TAG}"
    ports:
      - "8000:8000"
    env_file:
      - .env
